module.exports = {
    monthsEq: '(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|(Nov|Dec)(?:ember)?)',
    months: /(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|(Nov|Dec)(?:ember)?)/ig,
    words: /words/i,
    dates: /dates/i,
    normal: /normal/i,
    isArray: /\[.*\]/,
    startValue: /^./,
    endValue: /.$/,
    specialChars: /[^a-z0-9]+/ig,
    digits: /^[0-9\/\s\-\.\,]+$/g,
    strictDigit: /[0-9]+/g,
    flagsAtEnd: /((\/i?g?))$/,
    onlyDigits: /^\d+$/g,
    strictAlphabets: /^[a-z]+$/ig,
    strictSpecialChars: /^[^a-z0-9]+$/ig,
    alphaNumeric: /^(?=.*[a-z])(?=.*[0-9])[a-z0-9]+$/ig,
    alphaNumericWithSpecialChars: /^(?=.*[a-z])(?=.*[0-9])[a-z0-9-.\/!@#$%^&*\(\).~`\s]+$/ig,
    amounts: /^[0-9.,\-\+]+$/g,
    alphaSpecialChars: /^[a-z-.\/!@#$%^&*\(\)\s.~`]+$/ig,
    digitsSpecialChars: /^[0-9-.\/!@#$%^&*\(\).~`\s]+$/g
}